#!/bin/bash

# JKP Katastar - Configuration Migration Script
# Helps users migrate from hardcoded values to the new configuration system

set -e

echo "🔄 JKP Katastar - Configuration Migration"
echo "========================================="

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/deployment.config"
EXAMPLE_CONFIG="$SCRIPT_DIR/deployment.config.example"

# Function to detect current VPS IP from existing files
detect_current_config() {
    local detected_ip=""
    local detected_repo=""

    # Try to find IP from deploy-vps.sh
    if [ -f "$SCRIPT_DIR/deploy-vps.sh" ]; then
        detected_ip=$(grep -o 'VPS_HOST="[^"]*"' "$SCRIPT_DIR/deploy-vps.sh" | cut -d'"' -f2 | head -1)
    fi

    # Try to find repository from workflow
    if [ -f "$SCRIPT_DIR/.github/workflows/deploy.yml" ]; then
        detected_repo=$(grep -o 'constantine2nd/JKPKatastar' "$SCRIPT_DIR/.github/workflows/deploy.yml" | head -1)
    fi

    # Fallback to scanning all files for IP pattern
    if [ -z "$detected_ip" ]; then
        detected_ip=$(grep -r "194\.146\.58\.124" "$SCRIPT_DIR" 2>/dev/null | head -1 | grep -o "194\.146\.58\.124" || echo "")
    fi

    echo "DETECTED_VPS_IP=\"$detected_ip\""
    echo "DETECTED_REPO=\"$detected_repo\""
}

# Function to backup existing files
backup_files() {
    local backup_dir="$SCRIPT_DIR/backup-$(date +%Y%m%d-%H%M%S)"

    echo "📦 Creating backup directory: $backup_dir"
    mkdir -p "$backup_dir"

    # Backup files that will be modified
    local files_to_backup=(
        "deploy-vps.sh"
        "health-check.sh"
        "test-vps-ready.sh"
        "setup-vps-server.sh"
        ".github/workflows/deploy.yml"
    )

    for file in "${files_to_backup[@]}"; do
        if [ -f "$SCRIPT_DIR/$file" ]; then
            local backup_path="$backup_dir/$file"
            mkdir -p "$(dirname "$backup_path")"
            cp "$SCRIPT_DIR/$file" "$backup_path"
            echo "  ✅ Backed up: $file"
        fi
    done

    echo "✅ Backup completed: $backup_dir"
}

# Function to create new configuration file
create_config() {
    local vps_ip="$1"
    local repo="$2"

    echo "📝 Creating new configuration file..."

    if [ -f "$CONFIG_FILE" ]; then
        echo "⚠️  Configuration file already exists: $CONFIG_FILE"
        read -p "Do you want to overwrite it? [y/N]: " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "❌ Migration cancelled"
            return 1
        fi
    fi

    # Create configuration from template
    cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# JKP Katastar - Deployment Configuration
# Generated by migration script on $(date)

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================

# VPS Server Details
export VPS_HOST="${vps_ip:-194.146.58.124}"
export VPS_USER="root"
export VPS_PORT="22"

# =============================================================================
# PROJECT CONFIGURATION
# =============================================================================

# Project Details
export PROJECT_NAME="JKPKatastar"
export GITHUB_REPOSITORY="${repo:-constantine2nd/JKPKatastar}"
export DEFAULT_BRANCH="main"

# Directory Structure
export DEPLOY_DIR="/opt/jkp-katastar"
export DATA_DIR="/opt/jkp-katastar/data"
export LOGS_DIR="/opt/jkp-katastar/logs"
export BACKUP_DIR="/opt/jkp-katastar/backups"

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================

# Service Ports
export FRONTEND_PORT="3000"
export BACKEND_PORT="5000"
export MONGODB_PORT="27017"

# Service URLs (auto-generated)
export FRONTEND_URL="http://\${VPS_HOST}:\${FRONTEND_PORT}"
export BACKEND_URL="http://\${VPS_HOST}:\${BACKEND_PORT}"
export API_URL="\${BACKEND_URL}/api"
export HEALTH_URL="\${API_URL}/health"

# Application Environment
export NODE_ENV="production"
export MONGO_DATABASE="graves_prod"
export MONGO_USERNAME="admin"

# Map Center (Temerin, Serbia)
export MAP_CENTER_LAT="45.2671"
export MAP_CENTER_LON="19.8335"

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================

# Docker Configuration
export COMPOSE_PROJECT_NAME="jkp-katastar"
export DOCKER_BUILDKIT="1"

# Deployment Settings
export DEPLOYMENT_TIMEOUT="300"
export SERVICE_STARTUP_WAIT="60"
export HEALTH_CHECK_RETRIES="30"
export HEALTH_CHECK_INTERVAL="5"

# Backup Settings
export BACKUP_RETENTION_COUNT="3"
export AUTO_BACKUP_BEFORE_DEPLOY="true"

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================

# Resource Limits (in MB)
export MIN_MEMORY_MB="256"
export MIN_DISK_MB="2048"
export DISK_WARNING_THRESHOLD="85"

# Log Settings
export LOG_MAX_SIZE="10m"
export LOG_MAX_FILES="3"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# SSH Settings
export SSH_KEY_PATH="~/.ssh/github_actions"
export SSH_KEY_COMMENT="github-actions@jkp-katastar"

# Firewall Ports
export ALLOWED_PORTS="22 3000 5000"

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Display configuration
show_config() {
    echo "🔧 JKP Katastar Configuration"
    echo "=========================="
    echo "VPS Host: \${VPS_HOST}"
    echo "Project: \${PROJECT_NAME}"
    echo "Repository: \${GITHUB_REPOSITORY}"
    echo "Frontend: \${FRONTEND_URL}"
    echo "Backend: \${BACKEND_URL}"
    echo "API: \${API_URL}"
    echo "Health: \${HEALTH_URL}"
    echo "Database: \${MONGO_DATABASE}"
}

# Validate configuration
validate_config() {
    local errors=0

    if [ -z "\${VPS_HOST}" ] || [ "\${VPS_HOST}" = "your.vps.ip.address" ]; then
        echo "❌ Please set VPS_HOST to your actual VPS IP address"
        errors=\$((errors + 1))
    fi

    if [ -z "\${GITHUB_REPOSITORY}" ]; then
        echo "❌ Please set GITHUB_REPOSITORY"
        errors=\$((errors + 1))
    fi

    if [ \$errors -eq 0 ]; then
        echo "✅ Configuration is valid"
        return 0
    else
        echo "❌ Configuration has \$errors errors"
        return 1
    fi
}

# Handle arguments
case "\${1:-}" in
    "show")
        show_config
        ;;
    "validate")
        validate_config
        ;;
    *)
        echo "📦 JKP Katastar configuration loaded"
        echo "   Run 'source deployment.config show' to display"
        echo "   Run 'source deployment.config validate' to validate"
        ;;
esac
EOF

    chmod +x "$CONFIG_FILE"
    echo "✅ Configuration file created: $CONFIG_FILE"
}

# Function to update GitHub secrets documentation
update_documentation() {
    local vps_ip="$1"

    echo "📚 Updating documentation with your VPS IP..."

    # Update README.md with actual IP
    if [ -f "$SCRIPT_DIR/README.md" ] && [ -n "$vps_ip" ]; then
        sed -i.bak "s/your\.vps\.ip\.address/$vps_ip/g" "$SCRIPT_DIR/README.md"
        echo "  ✅ Updated README.md"
    fi
}

# Function to show GitHub secrets that need to be updated
show_github_secrets() {
    local vps_ip="$1"

    echo ""
    echo "🔑 GitHub Secrets Configuration"
    echo "==============================="
    echo ""
    echo "You need to add/update these secrets in your GitHub repository:"
    echo "Repository → Settings → Secrets and variables → Actions"
    echo ""
    echo "Required secrets:"
    echo "  VPS_HOST: $vps_ip"
    echo "  VPS_USER: root"
    echo "  VPS_SSH_KEY: (your SSH private key)"
    echo "  MONGO_PASSWORD: (your secure MongoDB password)"
    echo "  JWT_SECRET: (your secure JWT secret)"
    echo ""
    echo "URLs are auto-generated from VPS_HOST:"
    echo "  Frontend: http://$vps_ip:3000 (VPS_HOST + :3000)"
    echo "  Backend API: http://$vps_ip:5000/api (VPS_HOST + :5000/api)"
    echo ""
    echo "Optional secrets (for email notifications):"
    echo "  EMAIL_SERVICE: gmail"
    echo "  EMAIL_HOST: smtp.gmail.com"
    echo "  EMAIL_PORT: 587"
    echo "  EMAIL_USER: your-email@gmail.com"
    echo "  EMAIL_SECRET: your-app-password"
    echo ""
}

# Function to test the new configuration
test_configuration() {
    echo "🧪 Testing new configuration..."

    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"

        echo "Testing configuration validation..."
        if validate_config; then
            echo "✅ Configuration test passed"

            echo ""
            echo "📋 Configuration Summary:"
            show_config

            return 0
        else
            echo "❌ Configuration test failed"
            return 1
        fi
    else
        echo "❌ Configuration file not found: $CONFIG_FILE"
        return 1
    fi
}

# Main migration process
main() {
    echo ""
    echo "This script will:"
    echo "  1. Detect your current VPS IP and repository"
    echo "  2. Backup existing files"
    echo "  3. Create a new configuration file"
    echo "  4. Update documentation"
    echo "  5. Show GitHub secrets you need to set"
    echo ""

    read -p "Do you want to proceed with the migration? [Y/n]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "❌ Migration cancelled"
        exit 0
    fi

    echo ""
    echo "🔍 Step 1: Detecting current configuration..."
    eval "$(detect_current_config)"

    if [ -n "$DETECTED_VPS_IP" ]; then
        echo "  ✅ Detected VPS IP: $DETECTED_VPS_IP"
    else
        echo "  ⚠️  Could not detect VPS IP, using default"
        DETECTED_VPS_IP="194.146.58.124"
    fi

    if [ -n "$DETECTED_REPO" ]; then
        echo "  ✅ Detected repository: $DETECTED_REPO"
    else
        echo "  ⚠️  Could not detect repository, using default"
        DETECTED_REPO="constantine2nd/JKPKatastar"
    fi

    # Allow user to override detected values
    echo ""
    read -p "VPS IP address [$DETECTED_VPS_IP]: " user_vps_ip
    VPS_IP="${user_vps_ip:-$DETECTED_VPS_IP}"

    read -p "GitHub repository [$DETECTED_REPO]: " user_repo
    REPO="${user_repo:-$DETECTED_REPO}"

    echo ""
    echo "🔧 Step 2: Creating backup..."
    backup_files

    echo ""
    echo "📝 Step 3: Creating configuration..."
    create_config "$VPS_IP" "$REPO"

    echo ""
    echo "📚 Step 4: Updating documentation..."
    update_documentation "$VPS_IP"

    echo ""
    echo "🧪 Step 5: Testing configuration..."
    if test_configuration; then
        echo ""
        echo "🎉 Migration completed successfully!"

        show_github_secrets "$VPS_IP"

        echo ""
        echo "📋 Next Steps:"
        echo "  1. Review the configuration: source deployment.config show"
        echo "  2. Update GitHub secrets as shown above"
        echo "  3. Test deployment: ./deploy-vps.sh deploy"
        echo "  4. Run health check: ./health-check.sh"
        echo ""
        echo "📁 Backups stored in: $(ls -dt backup-* | head -1)"
        echo ""
    else
        echo ""
        echo "⚠️  Migration completed with warnings"
        echo "Please review and fix the configuration file: $CONFIG_FILE"
    fi
}

# Handle script arguments
case "${1:-}" in
    "help"|"-h"|"--help")
        echo "Usage: $0 [help|backup|test]"
        echo ""
        echo "Commands:"
        echo "  help   - Show this help"
        echo "  backup - Only create backup of existing files"
        echo "  test   - Only test existing configuration"
        echo ""
        echo "Default: Run full migration process"
        ;;
    "backup")
        backup_files
        ;;
    "test")
        test_configuration
        ;;
    *)
        main
        ;;
esac
