const VISITOR = "VISITOR";
const OFFICER = "OFFICER";
const ADMINISTRATOR = "ADMINISTRATOR";
const MAINTAINER = "MAINTAINER";
export { VISITOR, OFFICER, ADMINISTRATOR, MAINTAINER };

const REQUESTED = "REQUESTED";
const ACCEPTED = "ACCEPTED";
const DENIED = "DENIED";
export { REQUESTED, ACCEPTED, DENIED };

const FREE = "FREE";
const OCCUPIED = "OCCUPIED";
export { FREE, OCCUPIED };

